### ISSUE TITLE
support for mat-radio-button

### ISSUE THREAD

**Issue by aligit** [Plabbee/angular-material-contrast-fix#3]
Hey @Plabbee,
Thank you for creating this plugin. Do you think it would be possible to add support for mat-radio-button as well unless it requires you a lot of work. I'm not very confident on Sass programming but maybe if you provide me some hints I can send a PR

**Comment by Plabbee** [comment]
Hey @aligit , Sorry for the delay, new job.

What's the contrast issue with mat-radio-button you're seeing, I'm probs missing something silly but, it doesn't appear to use contrast colours for the palettes at all?

![image](https://github.com/Plabbee/angular-material-contrast-fix/assets/62303720/7dda8297-c2dc-43e8-808b-cfe7a5a56126)

**Comment by aligit** [comment]
Hey Plabbee, thanks for your answer. The contrast is not working at all

**Comment by Plabbee** [comment]
Hi again,

So the labels for the radio buttons don't use the contrast colours you set in your primary/accent/warn palettes. They instead pull from the form field theming:
![image](https://github.com/Plabbee/angular-material-contrast-fix/assets/62303720/0e511ad4-2011-41ae-89c6-62808f60146f)
![image](https://github.com/Plabbee/angular-material-contrast-fix/assets/62303720/89df455e-9e45-4515-aeb7-8bc9e16d4e02)
![image](https://github.com/Plabbee/angular-material-contrast-fix/assets/62303720/5fc79b30-a0cb-4431-9ece-bc8e88c57e22)

This will be because the labels are on your app background, rather than sitting on the primary/accent/warn palette colours, so this is appropriate.

Easiest way, if you're wanting to override the colours of the labels, would be to create some custom global styling to override this for radio buttons. The docs on theming your own components would be of use in achieving this: https://material.angular.io/guide/theming-your-components#reading-color-values
